export { Hero } from "./Hero";
export { About } from "./About";
export { Skills } from "./Skills";
export { Projects } from "./Projects";
export { Experience } from "./Experience";
export { Education } from "./Education";
export { CurrentlyLearning } from "./CurrentlyLearning";
export { Contact } from "./Contact";
export { AIAssistant } from "./AIAssistant";
